// Generated by `pnpm packs sync` from art/*/pages.json. Do not edit by hand.
// Draft pages are only referenced in development, so production bundles leave their art out.
import type { TracedPackSource } from '@/lib/templates/traced'
import oceanFriendsFishFlower from '@/lib/templates/ocean-friends/fish-flower.json'
import oceanFriendsTurtleFlower from '@/lib/templates/ocean-friends/turtle-flower.json'
import oceanFriendsShellBloom from '@/lib/templates/ocean-friends/shell-bloom.json'
import oceanFriendsStarfishWaves from '@/lib/templates/ocean-friends/starfish-waves.json'
import oceanFriendsOctopusHug from '@/lib/templates/ocean-friends/octopus-hug.json'
import oceanFriendsPufferBloom from '@/lib/templates/ocean-friends/puffer-bloom.json'
import oceanFriendsWhaleCircle from '@/lib/templates/ocean-friends/whale-circle.json'
import oceanFriendsCrabCove from '@/lib/templates/ocean-friends/crab-cove.json'
import oceanFriendsSeahorseSway from '@/lib/templates/ocean-friends/seahorse-sway.json'
import oceanFriendsJellyDance from '@/lib/templates/ocean-friends/jelly-dance.json'
import oceanFriendsDolphinJump from '@/lib/templates/ocean-friends/dolphin-jump.json'
import oceanFriendsSealPup from '@/lib/templates/ocean-friends/seal-pup.json'
import oceanFriendsClownfishHome from '@/lib/templates/ocean-friends/clownfish-home.json'
import oceanFriendsStingrayGlide from '@/lib/templates/ocean-friends/stingray-glide.json'
import oceanFriendsOtterFloat from '@/lib/templates/ocean-friends/otter-float.json'
import oceanFriendsSharkSmile from '@/lib/templates/ocean-friends/shark-smile.json'
import safariGardenLionBloom from '@/lib/templates/safari-garden/lion-bloom.json'
import safariGardenGiraffeGarden from '@/lib/templates/safari-garden/giraffe-garden.json'
import safariGardenElephantShower from '@/lib/templates/safari-garden/elephant-shower.json'
import safariGardenZebraMeadow from '@/lib/templates/safari-garden/zebra-meadow.json'
import safariGardenHippoLilypad from '@/lib/templates/safari-garden/hippo-lilypad.json'
import safariGardenMonkeyVine from '@/lib/templates/safari-garden/monkey-vine.json'
import safariGardenRhinoFriend from '@/lib/templates/safari-garden/rhino-friend.json'
import safariGardenCheetahNap from '@/lib/templates/safari-garden/cheetah-nap.json'
import safariGardenParrotPerch from '@/lib/templates/safari-garden/parrot-perch.json'
import safariGardenFlamingoPond from '@/lib/templates/safari-garden/flamingo-pond.json'
import safariGardenMeerkatLookout from '@/lib/templates/safari-garden/meerkat-lookout.json'
import safariGardenTortoiseTrail from '@/lib/templates/safari-garden/tortoise-trail.json'
import safariGardenToucanTreetop from '@/lib/templates/safari-garden/toucan-treetop.json'
import safariGardenGorillaFlower from '@/lib/templates/safari-garden/gorilla-flower.json'
import safariGardenChameleonCurl from '@/lib/templates/safari-garden/chameleon-curl.json'
import safariGardenOstrichStrut from '@/lib/templates/safari-garden/ostrich-strut.json'
import easterGardenBunnyBloom from '@/lib/templates/easter-garden/bunny-bloom.json'
import easterGardenEggBasket from '@/lib/templates/easter-garden/egg-basket.json'
import easterGardenChickHatch from '@/lib/templates/easter-garden/chick-hatch.json'
import easterGardenPaintedEgg from '@/lib/templates/easter-garden/painted-egg.json'
import easterGardenLambMeadow from '@/lib/templates/easter-garden/lamb-meadow.json'
import easterGardenTulipPot from '@/lib/templates/easter-garden/tulip-pot.json'
import easterGardenDucklingPuddle from '@/lib/templates/easter-garden/duckling-puddle.json'
import easterGardenButterflyGarden from '@/lib/templates/easter-garden/butterfly-garden.json'
import easterGardenCarrotPatch from '@/lib/templates/easter-garden/carrot-patch.json'
import easterGardenEggHunt from '@/lib/templates/easter-garden/egg-hunt.json'
import easterGardenHenNest from '@/lib/templates/easter-garden/hen-nest.json'
import easterGardenSpringWreath from '@/lib/templates/easter-garden/spring-wreath.json'
import easterGardenBunnyWagon from '@/lib/templates/easter-garden/bunny-wagon.json'
import easterGardenSnailDaisy from '@/lib/templates/easter-garden/snail-daisy.json'
import easterGardenBeeBlossom from '@/lib/templates/easter-garden/bee-blossom.json'
import easterGardenEggBalloon from '@/lib/templates/easter-garden/egg-balloon.json'
import christmasGardenTreeStar from '@/lib/templates/christmas-garden/tree-star.json'
import christmasGardenSnowmanScarf from '@/lib/templates/christmas-garden/snowman-scarf.json'
import christmasGardenReindeerBells from '@/lib/templates/christmas-garden/reindeer-bells.json'
import christmasGardenGingerbreadHouse from '@/lib/templates/christmas-garden/gingerbread-house.json'
import christmasGardenPenguinGift from '@/lib/templates/christmas-garden/penguin-gift.json'
import christmasGardenPoinsettiaBloom from '@/lib/templates/christmas-garden/poinsettia-bloom.json'
import christmasGardenStockingPair from '@/lib/templates/christmas-garden/stocking-pair.json'
import christmasGardenHollyWreath from '@/lib/templates/christmas-garden/holly-wreath.json'
import christmasGardenRobinHolly from '@/lib/templates/christmas-garden/robin-holly.json'
import christmasGardenSleighGifts from '@/lib/templates/christmas-garden/sleigh-gifts.json'
import christmasGardenPolarBearCocoa from '@/lib/templates/christmas-garden/polar-bear-cocoa.json'
import christmasGardenSnowGlobe from '@/lib/templates/christmas-garden/snow-globe.json'
import christmasGardenGingerbreadFriend from '@/lib/templates/christmas-garden/gingerbread-friend.json'
import christmasGardenBellsBow from '@/lib/templates/christmas-garden/bells-bow.json'
import christmasGardenOrnamentBloom from '@/lib/templates/christmas-garden/ornament-bloom.json'
import christmasGardenFoxLantern from '@/lib/templates/christmas-garden/fox-lantern.json'
import zenMandalasLotusBloom from '@/lib/templates/zen-mandalas/lotus-bloom.json'
import zenMandalasFernSpiral from '@/lib/templates/zen-mandalas/fern-spiral.json'
import zenMandalasCherryBlossom from '@/lib/templates/zen-mandalas/cherry-blossom.json'
import zenMandalasGinkgoWheel from '@/lib/templates/zen-mandalas/ginkgo-wheel.json'
import zenMandalasPeonyMedallion from '@/lib/templates/zen-mandalas/peony-medallion.json'
import zenMandalasRoseWindow from '@/lib/templates/zen-mandalas/rose-window.json'
import zenMandalasTropicalLeaves from '@/lib/templates/zen-mandalas/tropical-leaves.json'
import zenMandalasWildflowerRing from '@/lib/templates/zen-mandalas/wildflower-ring.json'
import zenMandalasDahliaBurst from '@/lib/templates/zen-mandalas/dahlia-burst.json'
import zenMandalasIrisCrown from '@/lib/templates/zen-mandalas/iris-crown.json'
import zenMandalasPoppyCircle from '@/lib/templates/zen-mandalas/poppy-circle.json'
import zenMandalasLavenderOlive from '@/lib/templates/zen-mandalas/lavender-olive.json'
import flowersGardenSunflowerSmile from '@/lib/templates/flowers-garden/sunflower-smile.json'
import flowersGardenDaisyTrio from '@/lib/templates/flowers-garden/daisy-trio.json'
import flowersGardenRoseFriend from '@/lib/templates/flowers-garden/rose-friend.json'
import flowersGardenWateringCan from '@/lib/templates/flowers-garden/watering-can.json'
import flowersGardenLadybugLeaf from '@/lib/templates/flowers-garden/ladybug-leaf.json'
import flowersGardenPotTrio from '@/lib/templates/flowers-garden/pot-trio.json'
import flowersGardenFrogLily from '@/lib/templates/flowers-garden/frog-lily.json'
import flowersGardenGardenGate from '@/lib/templates/flowers-garden/garden-gate.json'
import flowersGardenHummingbirdSip from '@/lib/templates/flowers-garden/hummingbird-sip.json'
import flowersGardenBirdhouseBloom from '@/lib/templates/flowers-garden/birdhouse-bloom.json'
import flowersGardenBouquetBow from '@/lib/templates/flowers-garden/bouquet-bow.json'
import flowersGardenDandelionPuff from '@/lib/templates/flowers-garden/dandelion-puff.json'
import flowersGardenCaterpillarClimb from '@/lib/templates/flowers-garden/caterpillar-climb.json'
import flowersGardenFlowerWheelbarrow from '@/lib/templates/flowers-garden/flower-wheelbarrow.json'
import flowersGardenPansyFace from '@/lib/templates/flowers-garden/pansy-face.json'
import flowersGardenRainbowFlowers from '@/lib/templates/flowers-garden/rainbow-flowers.json'
import oceanFriendsTwoWalrusWave from '@/lib/templates/ocean-friends-two/walrus-wave.json'
import oceanFriendsTwoNarwhalSwirl from '@/lib/templates/ocean-friends-two/narwhal-swirl.json'
import oceanFriendsTwoManateeMunch from '@/lib/templates/ocean-friends-two/manatee-munch.json'
import oceanFriendsTwoLobsterHello from '@/lib/templates/ocean-friends-two/lobster-hello.json'
import oceanFriendsTwoPuffinRock from '@/lib/templates/ocean-friends-two/puffin-rock.json'
import oceanFriendsTwoHermitCrabShell from '@/lib/templates/ocean-friends-two/hermit-crab-shell.json'
import oceanFriendsTwoAngelfishReef from '@/lib/templates/ocean-friends-two/angelfish-reef.json'
import oceanFriendsTwoNautilusSpiral from '@/lib/templates/ocean-friends-two/nautilus-spiral.json'
import oceanFriendsTwoSunfishDrift from '@/lib/templates/ocean-friends-two/sunfish-drift.json'
import oceanFriendsTwoSubmarinePeek from '@/lib/templates/ocean-friends-two/submarine-peek.json'
import oceanFriendsTwoBelugaBubbles from '@/lib/templates/ocean-friends-two/beluga-bubbles.json'
import oceanFriendsTwoOrcaSplash from '@/lib/templates/ocean-friends-two/orca-splash.json'
import oceanFriendsTwoSeagullSandcastle from '@/lib/templates/ocean-friends-two/seagull-sandcastle.json'
import oceanFriendsTwoShrimpCurl from '@/lib/templates/ocean-friends-two/shrimp-curl.json'
import oceanFriendsTwoFlyingFish from '@/lib/templates/ocean-friends-two/flying-fish.json'
import oceanFriendsTwoPelicanPost from '@/lib/templates/ocean-friends-two/pelican-post.json'
import safariGardenTwoBearCub from '@/lib/templates/safari-garden-two/bear-cub.json'
import safariGardenTwoPandaBamboo from '@/lib/templates/safari-garden-two/panda-bamboo.json'
import safariGardenTwoKoalaHug from '@/lib/templates/safari-garden-two/koala-hug.json'
import safariGardenTwoKangarooPouch from '@/lib/templates/safari-garden-two/kangaroo-pouch.json'
import safariGardenTwoCamelDunes from '@/lib/templates/safari-garden-two/camel-dunes.json'
import safariGardenTwoCrocodileGrin from '@/lib/templates/safari-garden-two/crocodile-grin.json'
import safariGardenTwoSlothHang from '@/lib/templates/safari-garden-two/sloth-hang.json'
import safariGardenTwoLemurTail from '@/lib/templates/safari-garden-two/lemur-tail.json'
import safariGardenTwoPeacockFan from '@/lib/templates/safari-garden-two/peacock-fan.json'
import safariGardenTwoRedPandaNap from '@/lib/templates/safari-garden-two/red-panda-nap.json'
import safariGardenTwoTreeFrogLeaf from '@/lib/templates/safari-garden-two/tree-frog-leaf.json'
import safariGardenTwoOkapiStripes from '@/lib/templates/safari-garden-two/okapi-stripes.json'
import safariGardenTwoArmadilloRoll from '@/lib/templates/safari-garden-two/armadillo-roll.json'
import safariGardenTwoButterflyBloom from '@/lib/templates/safari-garden-two/butterfly-bloom.json'
import safariGardenTwoFennecFox from '@/lib/templates/safari-garden-two/fennec-fox.json'
import safariGardenTwoWarthogPuddle from '@/lib/templates/safari-garden-two/warthog-puddle.json'
import christmasGardenTwoSantaWave from '@/lib/templates/christmas-garden-two/santa-wave.json'
import christmasGardenTwoElfWrapping from '@/lib/templates/christmas-garden-two/elf-wrapping.json'
import christmasGardenTwoCandyCaneBow from '@/lib/templates/christmas-garden-two/candy-cane-bow.json'
import christmasGardenTwoCandleTrio from '@/lib/templates/christmas-garden-two/candle-trio.json'
import christmasGardenTwoMittenPair from '@/lib/templates/christmas-garden-two/mitten-pair.json'
import christmasGardenTwoOwlHat from '@/lib/templates/christmas-garden-two/owl-hat.json'
import christmasGardenTwoTeddyGift from '@/lib/templates/christmas-garden-two/teddy-gift.json'
import christmasGardenTwoNutcrackerFriend from '@/lib/templates/christmas-garden-two/nutcracker-friend.json'
import christmasGardenTwoCookiesMilk from '@/lib/templates/christmas-garden-two/cookies-milk.json'
import christmasGardenTwoSnowBunny from '@/lib/templates/christmas-garden-two/snow-bunny.json'
import christmasGardenTwoKittenBauble from '@/lib/templates/christmas-garden-two/kitten-bauble.json'
import christmasGardenTwoToyTrain from '@/lib/templates/christmas-garden-two/toy-train.json'
import christmasGardenTwoRockingHorse from '@/lib/templates/christmas-garden-two/rocking-horse.json'
import christmasGardenTwoWinterCabin from '@/lib/templates/christmas-garden-two/winter-cabin.json'
import christmasGardenTwoToyDrum from '@/lib/templates/christmas-garden-two/toy-drum.json'
import christmasGardenTwoSnowflakeBloom from '@/lib/templates/christmas-garden-two/snowflake-bloom.json'

const DRAFTS_LISTED = process.env.NODE_ENV === 'development'

export const TRACED_PACK_SOURCES = [
  {
    id: 'ocean-friends',
    name: 'Ocean Friends',
    description: 'Sixteen sea friends: a flower fish and turtle, a shell with a pearl, a starfish, an octopus, a puffer fish, a whale, a crab, a seahorse, a jellyfish, a dolphin, a seal pup, a clownfish, a stingray, an otter and a friendly shark.',
    icon: 'fish',
    status: 'published',
    pages: [
      oceanFriendsFishFlower,
      oceanFriendsTurtleFlower,
      oceanFriendsShellBloom,
      oceanFriendsStarfishWaves,
      oceanFriendsOctopusHug,
      oceanFriendsPufferBloom,
      oceanFriendsWhaleCircle,
      oceanFriendsCrabCove,
      oceanFriendsSeahorseSway,
      oceanFriendsJellyDance,
      oceanFriendsDolphinJump,
      oceanFriendsSealPup,
      oceanFriendsClownfishHome,
      oceanFriendsStingrayGlide,
      oceanFriendsOtterFloat,
      oceanFriendsSharkSmile,
    ],
  },
  {
    id: 'safari-garden',
    name: 'Safari Garden',
    description: 'Sixteen wild friends among the flowers: a lion with a petal mane, a giraffe, an elephant, a zebra, a hippo, a monkey, a rhino, a sleepy cheetah, a parrot, a flamingo, meerkats, a tortoise, a toucan, a gorilla, a chameleon and an ostrich.',
    icon: 'paw-print',
    status: 'published',
    pages: [
      safariGardenLionBloom,
      safariGardenGiraffeGarden,
      safariGardenElephantShower,
      safariGardenZebraMeadow,
      safariGardenHippoLilypad,
      safariGardenMonkeyVine,
      safariGardenRhinoFriend,
      safariGardenCheetahNap,
      safariGardenParrotPerch,
      safariGardenFlamingoPond,
      safariGardenMeerkatLookout,
      safariGardenTortoiseTrail,
      safariGardenToucanTreetop,
      safariGardenGorillaFlower,
      safariGardenChameleonCurl,
      safariGardenOstrichStrut,
    ],
  },
  {
    id: 'easter-garden',
    name: 'Easter Garden',
    description: 'Sixteen springtime pictures: bunnies, an egg basket, a hatching chick, a painted egg, a lamb, tulips, a duckling, a butterfly, a carrot patch, an egg hunt, a hen on her nest, a spring wreath, a snail, a bee and an egg balloon.',
    icon: 'egg',
    status: 'published',
    pages: [
      easterGardenBunnyBloom,
      easterGardenEggBasket,
      easterGardenChickHatch,
      easterGardenPaintedEgg,
      easterGardenLambMeadow,
      easterGardenTulipPot,
      easterGardenDucklingPuddle,
      easterGardenButterflyGarden,
      easterGardenCarrotPatch,
      easterGardenEggHunt,
      easterGardenHenNest,
      easterGardenSpringWreath,
      easterGardenBunnyWagon,
      easterGardenSnailDaisy,
      easterGardenBeeBlossom,
      easterGardenEggBalloon,
    ],
  },
  {
    id: 'christmas-garden',
    name: 'Christmas Garden',
    description: 'Sixteen snowy pictures: a Christmas tree, a snowman, a reindeer, a gingerbread house and friend, a penguin, a poinsettia, stockings, a holly wreath, a robin, a sleigh, a polar bear, a snow globe, bells, a bauble and a fox.',
    icon: 'tree-pine',
    status: 'published',
    pages: [
      christmasGardenTreeStar,
      christmasGardenSnowmanScarf,
      christmasGardenReindeerBells,
      christmasGardenGingerbreadHouse,
      christmasGardenPenguinGift,
      christmasGardenPoinsettiaBloom,
      christmasGardenStockingPair,
      christmasGardenHollyWreath,
      christmasGardenRobinHolly,
      christmasGardenSleighGifts,
      christmasGardenPolarBearCocoa,
      christmasGardenSnowGlobe,
      christmasGardenGingerbreadFriend,
      christmasGardenBellsBow,
      christmasGardenOrnamentBloom,
      christmasGardenFoxLantern,
    ],
  },
  {
    id: 'zen-mandalas',
    name: 'Zen Mandalas',
    description: 'Twelve detailed mandalas for grown-ups to color: rings of lotus petals, ferns, cherry blossom, ginkgo, peonies, roses, tropical leaves, wildflowers, dahlias, irises, poppies, and lavender with olive, with finer areas and lighter outlines than the children\'s packs.',
    icon: 'leaf',
    status: 'draft',
    audience: 'grown-ups',
    pages: DRAFTS_LISTED
      ? [
        zenMandalasLotusBloom,
        zenMandalasFernSpiral,
        zenMandalasCherryBlossom,
        zenMandalasGinkgoWheel,
        zenMandalasPeonyMedallion,
        zenMandalasRoseWindow,
        zenMandalasTropicalLeaves,
        zenMandalasWildflowerRing,
        zenMandalasDahliaBurst,
        zenMandalasIrisCrown,
        zenMandalasPoppyCircle,
        zenMandalasLavenderOlive,
      ]
      : [],
  },
  {
    id: 'flowers-garden',
    name: 'Flowers Garden',
    description: 'Sixteen blooming pictures: a smiling sunflower, three daisies, a rose, a watering can, a ladybug, flower pots, a frog on a lily pad, a garden gate, a hummingbird, a birdhouse, a bouquet, a dandelion, a caterpillar, a wheelbarrow, a pansy and a rainbow.',
    icon: 'sprout',
    status: 'published',
    pages: [
      flowersGardenSunflowerSmile,
      flowersGardenDaisyTrio,
      flowersGardenRoseFriend,
      flowersGardenWateringCan,
      flowersGardenLadybugLeaf,
      flowersGardenPotTrio,
      flowersGardenFrogLily,
      flowersGardenGardenGate,
      flowersGardenHummingbirdSip,
      flowersGardenBirdhouseBloom,
      flowersGardenBouquetBow,
      flowersGardenDandelionPuff,
      flowersGardenCaterpillarClimb,
      flowersGardenFlowerWheelbarrow,
      flowersGardenPansyFace,
      flowersGardenRainbowFlowers,
    ],
  },
  {
    id: 'ocean-friends-two',
    name: 'Ocean Friends 2',
    description: 'Sixteen more sea friends: a walrus, a narwhal, a manatee, a lobster, a puffin, a hermit crab, an angelfish, a nautilus, a sunfish, a little submarine, a beluga, an orca, a seagull with a sandcastle, a shrimp, a flying fish and a pelican.',
    icon: 'shell',
    status: 'published',
    pages: [
      oceanFriendsTwoWalrusWave,
      oceanFriendsTwoNarwhalSwirl,
      oceanFriendsTwoManateeMunch,
      oceanFriendsTwoLobsterHello,
      oceanFriendsTwoPuffinRock,
      oceanFriendsTwoHermitCrabShell,
      oceanFriendsTwoAngelfishReef,
      oceanFriendsTwoNautilusSpiral,
      oceanFriendsTwoSunfishDrift,
      oceanFriendsTwoSubmarinePeek,
      oceanFriendsTwoBelugaBubbles,
      oceanFriendsTwoOrcaSplash,
      oceanFriendsTwoSeagullSandcastle,
      oceanFriendsTwoShrimpCurl,
      oceanFriendsTwoFlyingFish,
      oceanFriendsTwoPelicanPost,
    ],
  },
  {
    id: 'safari-garden-two',
    name: 'Safari Garden 2',
    description: 'Sixteen more wild friends among big flowers: a bear cub, a panda, a koala, a kangaroo, a camel, a crocodile, a sloth, a lemur, a peacock, a red panda, a tree frog, an okapi, an armadillo, a butterfly, a fennec fox and a warthog.',
    icon: 'bird',
    status: 'published',
    pages: [
      safariGardenTwoBearCub,
      safariGardenTwoPandaBamboo,
      safariGardenTwoKoalaHug,
      safariGardenTwoKangarooPouch,
      safariGardenTwoCamelDunes,
      safariGardenTwoCrocodileGrin,
      safariGardenTwoSlothHang,
      safariGardenTwoLemurTail,
      safariGardenTwoPeacockFan,
      safariGardenTwoRedPandaNap,
      safariGardenTwoTreeFrogLeaf,
      safariGardenTwoOkapiStripes,
      safariGardenTwoArmadilloRoll,
      safariGardenTwoButterflyBloom,
      safariGardenTwoFennecFox,
      safariGardenTwoWarthogPuddle,
    ],
  },
  {
    id: 'christmas-garden-two',
    name: 'Christmas Garden 2',
    description: 'Sixteen more Christmas pictures: Santa, an elf, candy canes, candles, mittens, an owl in a hat, a teddy in a gift box, a nutcracker, cookies and milk, a snow bunny, a kitten with a bauble, a toy train, a rocking horse, a snowy cabin, a toy drum and a big snowflake.',
    icon: 'snowflake',
    status: 'published',
    pages: [
      christmasGardenTwoSantaWave,
      christmasGardenTwoElfWrapping,
      christmasGardenTwoCandyCaneBow,
      christmasGardenTwoCandleTrio,
      christmasGardenTwoMittenPair,
      christmasGardenTwoOwlHat,
      christmasGardenTwoTeddyGift,
      christmasGardenTwoNutcrackerFriend,
      christmasGardenTwoCookiesMilk,
      christmasGardenTwoSnowBunny,
      christmasGardenTwoKittenBauble,
      christmasGardenTwoToyTrain,
      christmasGardenTwoRockingHorse,
      christmasGardenTwoWinterCabin,
      christmasGardenTwoToyDrum,
      christmasGardenTwoSnowflakeBloom,
    ],
  },
] as const satisfies readonly TracedPackSource[]
