// Generated by `pnpm packs sync` from art/*/pages.json. Do not edit by hand.
import type { TracedPackSource } from '@/lib/templates/traced'
import oceanFriendsFishFlower from '@/lib/templates/ocean-friends/fish-flower.json'
import oceanFriendsTurtleFlower from '@/lib/templates/ocean-friends/turtle-flower.json'
import oceanFriendsShellBloom from '@/lib/templates/ocean-friends/shell-bloom.json'
import oceanFriendsStarfishWaves from '@/lib/templates/ocean-friends/starfish-waves.json'
import oceanFriendsOctopusHug from '@/lib/templates/ocean-friends/octopus-hug.json'
import oceanFriendsPufferBloom from '@/lib/templates/ocean-friends/puffer-bloom.json'
import oceanFriendsWhaleCircle from '@/lib/templates/ocean-friends/whale-circle.json'
import oceanFriendsCrabCove from '@/lib/templates/ocean-friends/crab-cove.json'
import oceanFriendsSeahorseSway from '@/lib/templates/ocean-friends/seahorse-sway.json'
import oceanFriendsJellyDance from '@/lib/templates/ocean-friends/jelly-dance.json'
import oceanFriendsDolphinJump from '@/lib/templates/ocean-friends/dolphin-jump.json'
import oceanFriendsSealPup from '@/lib/templates/ocean-friends/seal-pup.json'
import oceanFriendsClownfishHome from '@/lib/templates/ocean-friends/clownfish-home.json'
import oceanFriendsStingrayGlide from '@/lib/templates/ocean-friends/stingray-glide.json'
import oceanFriendsOtterFloat from '@/lib/templates/ocean-friends/otter-float.json'
import oceanFriendsSharkSmile from '@/lib/templates/ocean-friends/shark-smile.json'
import safariGardenLionBloom from '@/lib/templates/safari-garden/lion-bloom.json'
import safariGardenGiraffeGarden from '@/lib/templates/safari-garden/giraffe-garden.json'
import safariGardenElephantShower from '@/lib/templates/safari-garden/elephant-shower.json'
import safariGardenZebraMeadow from '@/lib/templates/safari-garden/zebra-meadow.json'
import safariGardenHippoLilypad from '@/lib/templates/safari-garden/hippo-lilypad.json'
import safariGardenMonkeyVine from '@/lib/templates/safari-garden/monkey-vine.json'
import safariGardenRhinoFriend from '@/lib/templates/safari-garden/rhino-friend.json'
import safariGardenCheetahNap from '@/lib/templates/safari-garden/cheetah-nap.json'
import safariGardenParrotPerch from '@/lib/templates/safari-garden/parrot-perch.json'
import safariGardenFlamingoPond from '@/lib/templates/safari-garden/flamingo-pond.json'
import safariGardenMeerkatLookout from '@/lib/templates/safari-garden/meerkat-lookout.json'
import safariGardenTortoiseTrail from '@/lib/templates/safari-garden/tortoise-trail.json'
import safariGardenToucanTreetop from '@/lib/templates/safari-garden/toucan-treetop.json'
import safariGardenGorillaFlower from '@/lib/templates/safari-garden/gorilla-flower.json'
import safariGardenChameleonCurl from '@/lib/templates/safari-garden/chameleon-curl.json'
import safariGardenOstrichStrut from '@/lib/templates/safari-garden/ostrich-strut.json'
import easterGardenBunnyBloom from '@/lib/templates/easter-garden/bunny-bloom.json'
import easterGardenEggBasket from '@/lib/templates/easter-garden/egg-basket.json'
import easterGardenChickHatch from '@/lib/templates/easter-garden/chick-hatch.json'
import easterGardenPaintedEgg from '@/lib/templates/easter-garden/painted-egg.json'
import easterGardenLambMeadow from '@/lib/templates/easter-garden/lamb-meadow.json'
import easterGardenTulipPot from '@/lib/templates/easter-garden/tulip-pot.json'
import easterGardenDucklingPuddle from '@/lib/templates/easter-garden/duckling-puddle.json'
import easterGardenButterflyGarden from '@/lib/templates/easter-garden/butterfly-garden.json'
import easterGardenCarrotPatch from '@/lib/templates/easter-garden/carrot-patch.json'
import easterGardenEggHunt from '@/lib/templates/easter-garden/egg-hunt.json'
import easterGardenHenNest from '@/lib/templates/easter-garden/hen-nest.json'
import easterGardenSpringWreath from '@/lib/templates/easter-garden/spring-wreath.json'
import easterGardenBunnyWagon from '@/lib/templates/easter-garden/bunny-wagon.json'
import easterGardenSnailDaisy from '@/lib/templates/easter-garden/snail-daisy.json'
import easterGardenBeeBlossom from '@/lib/templates/easter-garden/bee-blossom.json'
import easterGardenEggBalloon from '@/lib/templates/easter-garden/egg-balloon.json'
import christmasGardenTreeStar from '@/lib/templates/christmas-garden/tree-star.json'
import christmasGardenSnowmanScarf from '@/lib/templates/christmas-garden/snowman-scarf.json'
import christmasGardenReindeerBells from '@/lib/templates/christmas-garden/reindeer-bells.json'
import christmasGardenGingerbreadHouse from '@/lib/templates/christmas-garden/gingerbread-house.json'
import christmasGardenPenguinGift from '@/lib/templates/christmas-garden/penguin-gift.json'
import christmasGardenPoinsettiaBloom from '@/lib/templates/christmas-garden/poinsettia-bloom.json'
import christmasGardenStockingPair from '@/lib/templates/christmas-garden/stocking-pair.json'
import christmasGardenHollyWreath from '@/lib/templates/christmas-garden/holly-wreath.json'
import christmasGardenRobinHolly from '@/lib/templates/christmas-garden/robin-holly.json'
import christmasGardenSleighGifts from '@/lib/templates/christmas-garden/sleigh-gifts.json'
import christmasGardenPolarBearCocoa from '@/lib/templates/christmas-garden/polar-bear-cocoa.json'
import christmasGardenSnowGlobe from '@/lib/templates/christmas-garden/snow-globe.json'
import christmasGardenGingerbreadFriend from '@/lib/templates/christmas-garden/gingerbread-friend.json'
import christmasGardenBellsBow from '@/lib/templates/christmas-garden/bells-bow.json'
import christmasGardenOrnamentBloom from '@/lib/templates/christmas-garden/ornament-bloom.json'
import christmasGardenFoxLantern from '@/lib/templates/christmas-garden/fox-lantern.json'

export const TRACED_PACK_SOURCES = [
  {
    id: 'ocean-friends',
    name: 'Ocean Friends',
    description: 'Sixteen sea friends: a flower fish and turtle, a shell with a pearl, a starfish, an octopus, a puffer fish, a whale, a crab, a seahorse, a jellyfish, a dolphin, a seal pup, a clownfish, a stingray, an otter and a friendly shark.',
    icon: 'fish',
    status: 'published',
    pages: [
      oceanFriendsFishFlower,
      oceanFriendsTurtleFlower,
      oceanFriendsShellBloom,
      oceanFriendsStarfishWaves,
      oceanFriendsOctopusHug,
      oceanFriendsPufferBloom,
      oceanFriendsWhaleCircle,
      oceanFriendsCrabCove,
      oceanFriendsSeahorseSway,
      oceanFriendsJellyDance,
      oceanFriendsDolphinJump,
      oceanFriendsSealPup,
      oceanFriendsClownfishHome,
      oceanFriendsStingrayGlide,
      oceanFriendsOtterFloat,
      oceanFriendsSharkSmile,
    ],
  },
  {
    id: 'safari-garden',
    name: 'Safari Garden',
    description: 'Sixteen wild friends among the flowers: a lion with a petal mane, a giraffe, an elephant, a zebra, a hippo, a monkey, a rhino, a sleepy cheetah, a parrot, a flamingo, meerkats, a tortoise, a toucan, a gorilla, a chameleon and an ostrich.',
    icon: 'paw-print',
    status: 'published',
    pages: [
      safariGardenLionBloom,
      safariGardenGiraffeGarden,
      safariGardenElephantShower,
      safariGardenZebraMeadow,
      safariGardenHippoLilypad,
      safariGardenMonkeyVine,
      safariGardenRhinoFriend,
      safariGardenCheetahNap,
      safariGardenParrotPerch,
      safariGardenFlamingoPond,
      safariGardenMeerkatLookout,
      safariGardenTortoiseTrail,
      safariGardenToucanTreetop,
      safariGardenGorillaFlower,
      safariGardenChameleonCurl,
      safariGardenOstrichStrut,
    ],
  },
  {
    id: 'easter-garden',
    name: 'Easter Garden',
    description: 'Sixteen springtime pictures: bunnies, an egg basket, a hatching chick, a painted egg, a lamb, tulips, a duckling, a butterfly, a carrot patch, an egg hunt, a hen on her nest, a spring wreath, a snail, a bee and an egg balloon.',
    icon: 'egg',
    status: 'published',
    pages: [
      easterGardenBunnyBloom,
      easterGardenEggBasket,
      easterGardenChickHatch,
      easterGardenPaintedEgg,
      easterGardenLambMeadow,
      easterGardenTulipPot,
      easterGardenDucklingPuddle,
      easterGardenButterflyGarden,
      easterGardenCarrotPatch,
      easterGardenEggHunt,
      easterGardenHenNest,
      easterGardenSpringWreath,
      easterGardenBunnyWagon,
      easterGardenSnailDaisy,
      easterGardenBeeBlossom,
      easterGardenEggBalloon,
    ],
  },
  {
    id: 'christmas-garden',
    name: 'Christmas Garden',
    description: 'Sixteen snowy pictures: a Christmas tree, a snowman, a reindeer, a gingerbread house and friend, a penguin, a poinsettia, stockings, a holly wreath, a robin, a sleigh, a polar bear, a snow globe, bells, a bauble and a fox.',
    icon: 'tree-pine',
    status: 'published',
    pages: [
      christmasGardenTreeStar,
      christmasGardenSnowmanScarf,
      christmasGardenReindeerBells,
      christmasGardenGingerbreadHouse,
      christmasGardenPenguinGift,
      christmasGardenPoinsettiaBloom,
      christmasGardenStockingPair,
      christmasGardenHollyWreath,
      christmasGardenRobinHolly,
      christmasGardenSleighGifts,
      christmasGardenPolarBearCocoa,
      christmasGardenSnowGlobe,
      christmasGardenGingerbreadFriend,
      christmasGardenBellsBow,
      christmasGardenOrnamentBloom,
      christmasGardenFoxLantern,
    ],
  },
] as const satisfies readonly TracedPackSource[]
